server:
  listen_host: 127.0.0.1
  listen_port: 5432

morpfw:
  scan: []

application:
  mounted_apps: []
  new_user_state: active
  dburi: 'sqlite:///%(here)s/app.db'
  compositekey_separator: '!!!!'
  authn_policy: morpfw.authn.noauth:AuthnPolicy
  authn_policy_settings: {}
  development_mode: true

worker:
  enabled: false
  celery_settings: {}

security:
  allowed_nets:
    - 127.0.0.1/32

jwtauth:
  master_secret: secret
  leeway: 10
  allow_refresh: true

